// https://oj.vnoi.info/problem/hp_thpt_22_a
// Created: Minh Triet
// Date: 31/03/2026

#pragma GCC optimize("O3,unroll-loops")
#pragma GCC target("avx2,bmi,bmi2,lzcnt,popcnt")
#include <bits/stdc++.h>
using namespace std;

void solve()
{
    string s;
    cin >> s;

    for(int i = 0 ; i < (int)s.length() ; i ++)
    {
        
    }
}

signed main()
{
    ios::sync_with_stdio(false);
    cin.tie(0);


}